/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author darwing30
 */
public class V_Agregar extends javax.swing.JFrame {

    /**
     * Creates new form V_Partida
     */
    public V_Agregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        label_tipo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_numero = new javax.swing.JTextField();
        text_tipo = new javax.swing.JTextField();
        text_precio = new javax.swing.JTextField();
        bttn_enviar = new javax.swing.JButton();
        label_resultado = new javax.swing.JLabel();
        text_resultado = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(28, 28, 9));
        jLabel2.setText("Informe");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        label_tipo.setFont(new java.awt.Font("TlwgTypewriter", 0, 18)); // NOI18N
        label_tipo.setForeground(new java.awt.Color(1, 1, 1));
        label_tipo.setText("Tipo");
        getContentPane().add(label_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("TlwgTypewriter", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Número");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("TlwgTypewriter", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        text_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_numeroActionPerformed(evt);
            }
        });
        getContentPane().add(text_numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 44, -1));

        text_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tipoActionPerformed(evt);
            }
        });
        getContentPane().add(text_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 44, -1));

        text_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_precioActionPerformed(evt);
            }
        });
        getContentPane().add(text_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 70, 30));

        bttn_enviar.setText("Enviar");
        getContentPane().add(bttn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 90, 30));

        label_resultado.setFont(new java.awt.Font("TlwgTypewriter", 0, 18)); // NOI18N
        label_resultado.setForeground(new java.awt.Color(1, 1, 1));
        label_resultado.setText("Resultado");
        getContentPane().add(label_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        text_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(text_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 70, 30));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, 230));

        jLabel13.setBackground(new java.awt.Color(240, 244, 245));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/fondoanimales.jpg"))); // NOI18N
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_numeroActionPerformed

    private void text_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tipoActionPerformed

    private void text_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_precioActionPerformed

    private void text_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_resultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bttn_enviar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_resultado;
    private javax.swing.JLabel label_tipo;
    public javax.swing.JTextField text_numero;
    public javax.swing.JTextField text_precio;
    public javax.swing.JTextField text_resultado;
    public javax.swing.JTextField text_tipo;
    // End of variables declaration//GEN-END:variables
}
